"""place w/ marker rel

Revision ID: ce2542e14f2d
Revises: 8256b07413c8
Create Date: 2024-10-12 15:43:15.046418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce2542e14f2d'
down_revision: Union[str, None] = '8256b07413c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('head', sa.String(), nullable=False),
    sa.Column('subhead', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('link_inst', sa.String(), nullable=True),
    sa.Column('link_tt', sa.String(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.Column('marker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['marker_id'], ['marker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('marker', sa.Column('place_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'marker', 'place', ['place_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'marker', type_='foreignkey')
    op.drop_column('marker', 'place_id')
    op.drop_table('place')
    # ### end Alembic commands ###
