version: "3.9"

services:
  db:
    image: postgres:13.3
    container_name: postgres_db  
    environment:
      POSTGRES_DB: ${PSQL__POSTGRES_DB}
      POSTGRES_USER: ${PSQL__POSTGRES_USER}
      POSTGRES_PASSWORD: ${PSQL__POSTGRES_PASSWORD}
      POSTGRES_PORT: ${PSQL__POSTGRES_PORT}
    ports:
      - "${PSQL__POSTGRES_PORT}:5432"
    env_file:
      - '.env'
    
    volumes:
      - ./pgdata:/var/lib/postgresql/data

    networks:
      - my_network

  fastapi-app:
    build: ./app/.
    container_name: fastapi_app
    ports:
      - "90:${FASTApi__port}"
    depends_on:
      - db
    env_file:
      - '.env'

    networks:
      - my_network

networks:
  my_network: